[theme]
base = "light"
primaryColor = "#10B981"
backgroundColor = "#F8FAFC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false
